name: Deploy Patrol

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    permissions: write-all
    environment: staging
    steps:
      - uses: ahmadnassri/action-workflow-queue@v1
        with: 7200000 # 2h
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Staging
        run: |
          echo "Deployed Staging!"
          sleep 300
  deploy-prd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions: write-all
    needs: deploy-stg
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Production
        run: echo "Deployed Production!!"
