name: Deploy Patrol

on:
  push:
    branches:
      - main

# hello
# goodbye
# concurrency:
#   group: unity-dashboard-${{ github.ref }}
#   cancel-in-progress: false

jobs:
  deploy-stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    concurrency:
      group: job-${{ github.ref }}
      cancel-in-progress: false
    permissions: write-all
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Staging
        run: |
          echo "Deployed Staging!"
          sleep 300
  deploy-prd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions: write-all
    needs: deploy-stg
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Production
        run: echo "Deployed Production!!"
