name: Deploy Patrol

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}

jobs:
  deploy-stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    permissions: write-all
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Staging
        run: echo "Deployed Staging!"
  deploy-prd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions: write-all
    needs: deploy-stg
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Production
        run: echo "Deployed Production!!"
